// Alberta judges allowlist — sourced from the official Alberta Courts website.
// Court of King's Bench: https://albertacourts.ca/kb/about/justices-applications-judges
// Alberta Court of Justice: https://albertacourts.ca/cj/about-the-court/justices/list
// This verifies a typed name belongs to a real Alberta judge. It does NOT verify
// that the person typing it is that judge — only that the name is on the public list.

export const ALBERTA_JUDGES = [
  // --- Court of King's Bench — Leadership ---
  "Kent H. Davidson",
  "Ken G. Nielsen",
  "D. Blair Nixon",
  // --- Court of King's Bench — Justices ---
  "Donald Lee",
  "R. Paul Belzil",
  "Doreen A. Sulyma",
  "Eric F. Macklin",
  "John J. Gill",
  "Dallas K. Miller",
  "Paul R. Jeffrey",
  "Glen H. Poelman",
  "Rodney A. Jerke",
  "Peter B. Michalyshyn",
  "Craig M. Jones",
  "Charlene S. Anderson",
  "Glenda A. Campbell",
  "Corina Dario",
  "Debbie A. Yungwirth",
  "John S. Little",
  "Larry R.A. Ackerl",
  "Wayne N. Renke",
  "John T. Henderson",
  "Douglas R. Mah",
  "Gillian D. Marriott",
  "Avril B. Inglis",
  "James T. Eamon",
  "George R. Fraser",
  "Marilyn D. Slawinsky",
  "Michele H. Hollins",
  "Johnna C. Kubik",
  "Janice R. Ashcroft",
  "Steven N. Mandziuk",
  "Michael J. Lema",
  "Grant S. Dunlop",
  "Marta E. Burns",
  "Gaylene D.B. Kendell",
  "David A. Labrenz",
  "James T. Neilson",
  "Nancy F. Dilts",
  "Michael Kraus",
  "Susan L. Bercov",
  "D. Vaughan Hartigan",
  "Anna Loparco",
  "Susan E. Richardson",
  "Nicholas E. Devlin",
  "Johanna C. Price",
  "Melanie S. Hayes-Richards",
  "Nathan J. Whitling",
  "Shaina C. Leonard",
  "E. Jane Sidnell",
  "Barbara B. Johnston",
  "Denise J. Kiss",
  "Sherry L. Kachur",
  "Thomas G. Rothwell",
  "Ola Malik",
  "Lynn Michele Angotti",
  "Robert W. Armstrong",
  "Cheryl L. Arcand-Kootenay",
  "Lorena K. Harris",
  "Colin C.J. Feasby",
  "Eleanor J. Funk",
  "Michel H. Bourque",
  "Bob H. Aloneissi",
  "Nancy M. Carruthers",
  "Michael A. Marion",
  "Lisa A. Silver",
  "Allison G. Kuntz",
  "Kent J. Teskey",
  "Christopher D. Millsap",
  "Christopher A. Rickards",
  "Melanie R. Gaston",
  "Christopher D. Simard",
  "Shelley A. Moore",
  "Ayla K. Akgungor",
  "Jonathan D. Martin",
  "Darren J. Reed",
  "Chidinma B. Thompson",
  "Maureen J. McGuire",
  "Kelsey L. Becker Brookes",
  "Shane G. Parker",
  "Oliver Ho",
  "Derek Jugnauth",
  "Andrea L. Froese",
  "Ellery C. Lew",
  "Kathryn H. Oviatt",
  "Kristan A. McLeod",
  "Shannon W. Davis",
  "Caroline H.C. Magnan",
  "Jason L. Wilkins",
  "Peter D. Banks",
  "Parminder K. Johal",
  "Eric M. Adams",
  // --- Court of King's Bench — Applications Judges ---
  "J.L. Mason",
  "J.R. Farrington",
  "L.A. Mattis",
  "S. Latimer",
  "L. Smart",
  "L.R. Birkett",
  "B. Summers",
  "S. Wanke",
  "M. Park",
  // --- Alberta Court of Justice — Leadership ---
  "J. Hunter",
  "M.J. Durant",
  // --- Alberta Court of Justice — Edmonton Criminal ---
  "J.L. Lester",
  "K.S. Ahluwalia",
  "S.M.L. Bilodeau",
  "F. Bosscha",
  "R.K. Bodnarek",
  "R.W. Brandt",
  "M.M. Carminati",
  "M.M. Collinson",
  "J.L. Dixon",
  "M.C. Doyle",
  "C.D. Godfrey",
  "D.M. Groves",
  "D. Lefebvre",
  "G.B. Lepp",
  "F.K. MacDonald",
  "T. Marriott",
  "T.J. Matchett",
  "J.J. Moher",
  "T.J. O'Leary",
  "K. E. Palichuk",
  "S.N. Polkosnik",
  "F.Y. Roy",
  "C.J. Sharpe",
  "O. Shoyele",
  "L.C. Tchir",
  "R.E. Tibbitt",
  // --- Alberta Court of Justice — Edmonton Family and Youth ---
  "D.G. Hancock",
  "T.M. Bailey",
  "D. Dalton",
  "C.T.D. Du",
  "J.M. Filice",
  "G.B.N. Ho",
  "J.M. Janzen",
  "K.S.V. Linton",
  "J.C. Lloyd",
  "E. Madu",
  "K.E. McGowan",
  "M.J. Savaryn",
  "D. Zalmanowitz",
  // --- Alberta Court of Justice — Calgary Family and Youth ---
  "T.K.M. Davis",
  "F. Airth",
  "G.L.M. Benns",
  "S.H. Borsic",
  "G.H. Cornfield",
  "N.W. D'Souza",
  "D.B.H. Findlay",
  "E.M. Iredale",
  "T. LaRochelle",
  "D. Mah",
  "R.J. O'Gorman",
  "M.J. Shaften",
  "J.R. Shaw",
  // --- Alberta Court of Justice — Civil Division ---
  "D.B. Higa",
  "A. Argento",
  "L.L. Burt",
  "S.L. Corbett",
  "K. Haymour",
  "M.A. McCorquodale",
  "G. Shannon",
  "G.W. Sharek",
  "S. Stushnoff",
  "L.D. Young",
  // --- Alberta Court of Justice — Edmonton Region ---
  "G.D. Putnam",
  "T.W. Achtymichuk",
  "G.T. Annetts",
  "J.B. Champion",
  "S.A. Cleary",
  "T.T. Cunningham",
  "C-A. Downey",
  "C.D. Gardner",
  "A. Hemmerling",
  "W. Hendsbee",
  "J.M. Heudes",
  "J.P. Higgerty",
  "I.M.L. Ladouceur",
  "J. Morrison",
  "V.H. Myers",
  "C.G. Purvis",
  "G.A. Rice",
  "R.M. Saccomani",
  "J.E. Schaffter",
  "R.C. Shaigec",
  "J. Stuffco",
  "A.D.K. Wendel",
  // --- Alberta Court of Justice — Northern Region ---
  "Robert B. Marceau",
  "G.R. Ambrose",
  "M.B. Golden",
  "S. P. Hinkley",
  "B.R. Hougestol",
  "B.E. Langford",
  "C. A. Palmer",
  "J. Sihra",
  "C.K.W. Thietke",
  // --- Alberta Court of Justice — Central Region ---
  "J. Neustaeter",
  "W.A. Andreassen",
  "M. Brown",
  "J.A. Glass",
  "K. Goddard",
  "G. Hatch",
  "J.D. Holmes",
  "T. M. Scrase",
  "R.A. Snider",
  "W.A. Skinner",
  "G.L. Toni",
  "G.A.G. Yake",
  // --- Alberta Court of Justice — Calgary and Calgary Regional ---
  "E.J. Tolppanen",
  "S.L. Bagg",
  "A.J. Brown",
  "M.C. Christopher",
  "K.A. Crowshoe",
  "M.V. De Souza",
  "M.C. Dinkel",
  "G.S. Dunnigan",
  "S.M. Epp",
  "M.W. Ewenson",
  "K.L-L.Fahlman",
  "G.J. Gaschler",
  "M.L. Graham",
  "K.Z. Jivraj",
  "M.M. Keelaghan",
  "H.A. Lamoureux",
  "S. Mah",
  "I.L. Maharaj",
  "P.J. Mason",
  "K.R. McLeod",
  "K. Molle",
  "S.E. Pepper",
  "C.V. Pearce",
  "L.W. Robertson",
  "J.D. Sawa",
  "B.L. Shaw",
  "J. Shriar",
  "C.M. Skene",
  "G.D.M. Stirling",
  "M.T.C. Tyndale",
  "H.M. Van Harten",
  "K.R. Wilberg",
  "J.D. Williams",
  "G.K. Wong",
  // --- Alberta Court of Justice — Southern Region ---
  "E.D. Brooks",
  "K.R. Ailsby",
  "R.D. Anderson",
  "G. Auger",
  "J.W. Cowan",
  "M. Mastel",
  "G.S. Maxwell",
  "E. Olsen",
  "E.W. Peterson",
  "P.G. Pharo",
  "D.G. Redman",
  "C. Regier",
  // --- Alberta Court of Justice — Supernumerary Justices ---
  "M. Allen",
  "L.G. Anderson",
  "W.S. Andrew",
  "P. Ayotte",
  "P.B. Barley",
  "J.D. Bascom",
  "G.J. Burrell",
  "M.J. Burch",
  "R.R.M. Cochard",
  "C.L. Daniel",
];

function normalize(s) {
  return (s || '')
    .toLowerCase()
    .replace(/[.,*]/g, '')
    .replace(/'/g, '')
    .replace(/\s+/g, ' ')
    .trim();
}

// Returns array of matching judge display names for a query (for autocomplete).
export function searchJudges(query) {
  const q = normalize(query);
  if (!q) return [];
  return ALBERTA_JUDGES.filter((name) => {
    const n = normalize(name);
    return n === q || n.includes(' ' + q) || n.startsWith(q) || n.includes(q);
  }).slice(0, 8);
}

// Strict: returns the matched display name only if the query normalizes exactly
// to a known judge (full name or last name).
export function verifyJudge(query) {
  const q = normalize(query);
  if (!q) return null;
  for (const name of ALBERTA_JUDGES) {
    const n = normalize(name);
    if (n === q) return name;
    const last = n.split(' ').pop();
    if (q === last) return name;
  }
  return null;
}